apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: validation-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: validation-service
    spec:
      serviceAccountName: validation-service-sa
      containers:
        - name: validation-service
          image: nk95/validation-service:tagVersion
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: efs-volume
              mountPath: /mnt/m2/validation-service
      volumes:
        - name: efs-volume
          persistentVolumeClaim:
            claimName: test-pvc